version: "2"
services:
  builder:
    image: openlmis/dev:1
    volumes:
      - '.:/app'
      - '/home/user/.m2/repository/org/openlmis/openlmis-stockmanagement/5.1.2-SNAPSHOT:/build/libs'
    command:
      - './build.sh'
    environment:
      GRADLE_OPTS: '-Dorg.gradle.daemon=false'
